### ISSUE TITLE
[Docs] 메인 비즈니스 프로세스 모델을 작성한다

### ISSUE THREAD

**Issue by juneheel** [woorifisa-projects/HaeDal#4]
## 작업내용
메인 비즈니스 프로세스 모델을 작성한다

**Comment by image00** [comment]
4조 메인 비지니스 프로세스 모델
<br>

<img width="4208" alt="비즈니스 프로세스 모델 산출물" src="https://github.com/woorifisa-projects/HaeDal/assets/119517146/6acf4b13-91c9-4f5c-a406-1dfa98d43933">

**Comment by image00** [comment]
4조 메인 비지니스 프로세스 모델
<br>

<img width="4208" alt="비즈니스 프로세스 모델 산출물" src="https://github.com/woorifisa-projects/HaeDal/assets/119517146/6acf4b13-91c9-4f5c-a406-1dfa98d43933">
